### ISSUE TITLE
What certificates does the thumbprints represent?

### ISSUE THREAD

**Issue by jonolo-3** [EricHerlitz/Swedish-BankID-.NET-Core#2]
Hi, I've seen the thumbprints in appsettings:
"ServerCertificateThumbprint": "B581B136673317A3422D2E4B4F6BF3F77AF34798",
"RPCertificateThumbprint": "9312D6E82CAA742E5210293F333C397B02733425",

and I wonder what certificates they're thumbprints of and how they're used.

Thanks in advance.

**Comment by EricHerlitz** [comment]
Those should be the certificates from BankID. The server certificate is available in the documentation, the RP-certificate is downloadable from https://www.bankid.com/utvecklare/rp-info

The certificates are somewhat documented in this post, but use the latest available from the BankID-link above http://www.herlitz.nu/2017/09/13/integrating-with-swedish-bankid-and-.net/

**Comment by jonolo-3** [comment]
Thanks!
